// src/pages/Report.js

import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import Layout from '../components/Layout';
import { FileText, Download, Edit, Save, AlertCircle } from 'lucide-react';
import api from '../services/api';

const Report = () => {
  const { caseId } = useParams();
  const navigate = useNavigate();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [isEditing, setIsEditing] = useState(false);
  const [editedImpression, setEditedImpression] = useState('');
  const [downloadingPDF, setDownloadingPDF] = useState(false);

  useEffect(() => {
    fetchReport();
  }, [caseId]);

  const fetchReport = async () => {
    try {
      setLoading(true);
      const data = await api.report.getData(caseId);
      setReport(data.report);
      setEditedImpression(data.report.impression);
      setError(null);
    } catch (err) {
      setError(err.message);
      console.error('Failed to fetch report:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadPDF = async () => {
    try {
      setDownloadingPDF(true);
      const blob = await api.report.generatePDF(caseId);
      
      // Create download link
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `echo-report-${caseId}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err) {
      console.error('Failed to download PDF:', err);
      alert('Failed to download PDF. Please try again.');
    } finally {
      setDownloadingPDF(false);
    }
  };

  const handleSaveEdits = () => {
    // TODO: Save edited impression to backend
    setReport(prev => ({ ...prev, impression: editedImpression }));
    setIsEditing(false);
  };

  if (loading) {
    return (
      <Layout>
        <div className="flex items-center justify-center min-h-[60vh]">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600"></div>
        </div>
      </Layout>
    );
  }

  if (error) {
    return (
      <Layout>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-red-50 border border-red-200 rounded-lg p-6 text-red-700">
            <AlertCircle className="w-6 h-6 mb-2" />
            <p>Error loading report: {error}</p>
            <button 
              onClick={fetchReport}
              className="mt-4 px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700"
            >
              Try Again
            </button>
          </div>
        </div>
      </Layout>
    );
  }

  if (!report) {
    return (
      <Layout>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6 text-yellow-700">
            <AlertCircle className="w-6 h-6 mb-2" />
            <p>Report not found.</p>
          </div>
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="flex justify-between items-center mb-8">
          <div>
            <h1 className="text-3xl font-bold text-gray-800 mb-2">Clinical Report</h1>
            <p className="text-gray-600">Case ID: #{caseId}</p>
          </div>
          <button
            onClick={handleDownloadPDF}
            disabled={downloadingPDF}
            className="bg-green-600 text-white px-6 py-3 rounded-lg hover:bg-green-700 transition-colors flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Download className="w-5 h-5" />
            {downloadingPDF ? 'Downloading...' : 'Export PDF'}
          </button>
        </div>

        {/* Report Content */}
        <div className="bg-white rounded-xl shadow-lg p-8">
          {/* Report Header */}
          <div className="border-b pb-6 mb-6">
            <div className="flex items-center gap-3 mb-4">
              <FileText className="w-8 h-8 text-indigo-600" />
              <div>
                <h2 className="text-2xl font-bold text-gray-800">Echocardiography Analysis Report</h2>
                <p className="text-gray-600 mt-1">Generated by Echo AI System</p>
              </div>
            </div>
          </div>

          {/* Patient Information */}
          <div className="mb-8">
            <h3 className="text-lg font-bold text-gray-800 mb-4">Patient Information</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              <div>
                <p className="text-sm text-gray-600 mb-1">Patient Name</p>
                <p className="font-semibold text-gray-800">{report.patientName}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600 mb-1">Age</p>
                <p className="font-semibold text-gray-800">{report.age} years</p>
              </div>
              <div>
                <p className="text-sm text-gray-600 mb-1">Gender</p>
                <p className="font-semibold text-gray-800">{report.gender}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600 mb-1">Examination Date</p>
                <p className="font-semibold text-gray-800">{report.date}</p>
              </div>
            </div>
          </div>

          {/* Key Findings */}
          <div className="mb-8">
            <h3 className="text-lg font-bold text-gray-800 mb-4">Key Findings</h3>
            <div className="bg-gray-50 rounded-lg p-6 space-y-3">
              <FindingRow 
                label="Left Ventricular Ejection Fraction" 
                value={`${report.findings.ef}%`}
                note="(Mildly reduced)"
              />
              <FindingRow 
                label="End Diastolic Volume (EDV)" 
                value={`${report.findings.edv} mL`}
              />
              <FindingRow 
                label="End Systolic Volume (ESV)" 
                value={`${report.findings.esv} mL`}
              />
              <FindingRow 
                label="Wall Motion" 
                value={report.findings.wallMotion}
              />
              <FindingRow 
                label="Chamber Dimensions" 
                value="Within normal limits"
              />
            </div>
          </div>

          {/* Clinical Impression */}
          <div className="mb-8">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-bold text-gray-800">Clinical Impression</h3>
              {!isEditing ? (
                <button
                  onClick={() => setIsEditing(true)}
                  className="flex items-center gap-2 text-indigo-600 hover:text-indigo-700 text-sm font-medium"
                >
                  <Edit className="w-4 h-4" />
                  Edit
                </button>
              ) : (
                <button
                  onClick={handleSaveEdits}
                  className="flex items-center gap-2 text-green-600 hover:text-green-700 text-sm font-medium"
                >
                  <Save className="w-4 h-4" />
                  Save
                </button>
              )}
            </div>
            {isEditing ? (
              <textarea
                value={editedImpression}
                onChange={(e) => setEditedImpression(e.target.value)}
                rows="6"
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none resize-none"
              />
            ) : (
              <div className="bg-gray-50 rounded-lg p-6">
                <p className="text-gray-700 leading-relaxed">{report.impression}</p>
              </div>
            )}
          </div>

          {/* AI Disclaimer */}
          <div className="border-t pt-6">
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <p className="text-sm text-gray-700">
                <span className="font-semibold">Note:</span> This report was generated using AI-powered automated analysis. 
                Clinical interpretation and final diagnosis should be made by a qualified cardiologist.
              </p>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-4 mt-8">
            <button
              onClick={() => navigate('/dashboard')}
              className="flex-1 border-2 border-gray-300 text-gray-700 py-3 rounded-lg font-semibold hover:bg-gray-50 transition-colors"
            >
              Back to Dashboard
            </button>
            <button
              onClick={() => navigate(`/results/${caseId}`)}
              className="flex-1 border-2 border-indigo-600 text-indigo-600 py-3 rounded-lg font-semibold hover:bg-indigo-50 transition-colors"
            >
              View Results
            </button>
          </div>
        </div>
      </div>
    </Layout>
  );
};

const FindingRow = ({ label, value, note }) => {
  return (
    <div className="flex justify-between items-start py-2">
      <span className="text-gray-700 font-medium">{label}:</span>
      <div className="text-right">
        <span className="text-gray-900 font-semibold">{value}</span>
        {note && <span className="text-gray-600 text-sm ml-2">{note}</span>}
      </div>
    </div>
  );
};

export default Report;